### ISSUE TITLE
Error when setting sync tab DB connection.

### ISSUE THREAD

**Issue by f4w-git** [auth0/wp-auth0#920]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have installed the plugin successfully. 5.x to be specific. Trying to set the sync tab and get an error "Database Connection to sync WordPress with for non-social connections. Must begin with con_" Documentation all over Auth0 sites refer to the 4.x version of the plugin(which I installed successfully with sync capabilities.  Error is as follows: [22-Oct-2024 18:52:16 UTC] PHP Fatal error: Uncaught Auth0\SDK\Exception\ArgumentException: A value for id must be provided in /home/httpd/wp-content/plugins/wordpress/vendor/auth0/auth0-php/src/Exception/ArgumentException.php:51
Stack trace:
#0 /home/httpd/wp-content/plugins/wordpress/vendor/auth0/auth0-php/src/API/Management/Connections.php(93): Auth0\SDK\Exception\ArgumentException::missing('id')
#1 /home/httpdwp-content/plugins/wordpress/src/Actions/Configuration.php(939): Auth0\SDK\API\Management\Connections->get(NULL)
#2 /home/httpdwp-includes/class-wp-hook.php(326): Auth0\WordPress\Actions\Configuration->onUpdateSync(Array)
#3 /home/httpd/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#4 /home/httpd/wp-includes/formatting.php(5115): apply_filters('sanitize_option...', Array, 'auth0_sync', Array)
#5 /home/httpd/wp-includes/option.php(866): sanitize_option('auth0_sync', Array)
#6 /home/httpd/wp-admin/options.php(344): update_option('auth0_sync', Array)
#7 {main}
thrown in /home/httpd/wp-content/plugins/wordpress/vendor/auth0/auth0-php/src/Exception/ArgumentException.php on line 51

### Reproduction

input con_ database connection and get error.

### wp-auth0 version

5.2.1

### WordPress version

6.6.2

### PHP version

8.3

**Comment by f4w-git** [comment]
This is upon trying to save the database connection.

**Comment by kishore7snehil** [comment]
@f4w-git I can see that the setup is working fine and I would request you to double check if you aren't putting any extra spaces while adding the` connection_id.`

**Comment by f4w-git** [comment]
I am not putting any spaces in. I tried it again just now. It has to be with how I am installing then. The following is how the documentation says to install it. Is the following correct?

For standard WordPress installations, this command can be run from the wp-content/plugins sub-directory.

composer require symfony/http-client nyholm/psr7 auth0/wordpress:^5.0

**Comment by kishore7snehil** [comment]
@f4w-git Alternatively, you can try out downloading the plugin source code from this [link](https://github.com/auth0/wordpress/releases/tag/5.2.1) and place it in your `<application_name>/wp-content/plugins `folder. But, I would strongly recommend to use composer to upgrade plugin versions.

Moreover, this is how an ideal database connection value should look. Please be cautious of the trailing spaces.

![image](https://github.com/user-attachments/assets/68c62758-efa7-49df-bc6c-9e780b752ec0)

**Comment by f4w-git** [comment]
Then this has to be an install issue.  100% brand new clean wordpress install. I have used 3 different hosting solutions. Dreamhost and 2 local ubuntu installs.

Here are my install procedures for that plugin.
1.  I use this link to download. https://github.com/auth0/wordpress/releases/tag/5.2.1
2. install the plugin using Wordpress backend. It will not activate until I run composer:
3. CLI in the wordpress/wp-content/wordpress-5.2.1 composer require symfony/http-client nyholm/psr7 auth0/wordpress:^5.0
4. I can then activate the plugin.
5. input all of the domain, id and secret.
6. Sync page put in my DB connection. no spaces. The error still occurs. 

![Screenshot from 2024-12-06 10-15-08](https://github.com/user-attachments/assets/919e96a1-5714-4cad-b638-109c8e5dadab)
![Screenshot from 2024-12-06 10-14-44](https://github.com/user-attachments/assets/6f66d58d-4bc3-45e0-8541-1731e563c528)

**Comment by kishore7snehil** [comment]
@f4w-git  This can be then something to do with the $input['database'] data not passing correctly in the [onUpdateSync](https://github.com/auth0/wordpress/blob/169e917f060cd3b627ddc51fc840490c168bb673/src/Actions/Configuration.php#L939)

Can you put some debug points and check if the value of your connection passing correctly to the **$response**? If the value passed will be an empty string or null then you will face this issue.

**Comment by kishore7snehil** [comment]
Closing this issue due to inactivity. Please feel free to raise an issue [here](https://github.com/auth0/wp-auth0/issues).

**Comment by risturiz** [comment]
Hi, i can reproduce this too: ( put connection_id and try to save )

> PHP Fatal error:  Uncaught Auth0\SDK\Exception\ArgumentException: A value for `id` must be provided in /public_html/wp-content/plugins/auth0/vendor/auth0/auth0-php/src/Exception/ArgumentException.php:51

```
Stack trace:
#0 /public_html/wp-content/plugins/auth0/vendor/auth0/auth0-php/src/API/Management/Connections.php(93): Auth0\SDK\Exception\ArgumentException::missing()
#1 /public_html/wp-content/plugins/auth0/vendor/auth0/wordpress/src/Actions/Configuration.php(939): Auth0\SDK\API\Management\Connections->get()
#2 /public_html/wp-includes/class-wp-hook.php(326): Auth0\WordPress\Actions\Configuration->onUpdateSync()
#3 /public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#4 /public_html/wp-includes/formatting.php(5119): apply_filters()
#5 /public_html/wp-includes/option.php(1114): sanitize_option()
#6 /public_html/wp-includes/option.php(930): add_option()
#7 /public_html/wp-admin/options.php(344): update_option()
#8 {main}
  thrown in /public_html/wp-content/plugins/auth0/vendor/auth0/auth0-php/src/Exception/ArgumentException.php on line 51
```

Plugin Versión 5.4.0
PHP 8.3
WordPress 6.8.3
